### PR TITLE
Extend ItemSearch to Collection and ItemCollection

### PR DESCRIPTION
**Pull request by floriandeboissieu**
Many thanks for this very useful package!

This is a modest proposal to extend search function to pystac Collection and ItemCollection classes, as function `to_geodataframe` already accepts both classes in addition to pystac.Catalog.

My use case is that I would use a locally saved ItemCollection, but one could also think of re-using the search result for another search to progressively narrow down the results.

### CODE REVIEW

**Comment by jsignell** [comment]
Sorry for the slow response @floriandeboissieu this seems reasonable to me. I just want to make sure that the `to_geodataframe` helper works with those data types so I might add some tests to this PR if that is ok with you.

**Comment by floriandeboissieu** [comment]
No worries for the delay. Of course it is ok with me if you amend the PR or I could also add tests if you prefer.

Actually, I did not notice that you already had a test for collection (planet_disaster), and that it is passing the `to_geodataframe` successfully as Collection inherits and thus is also of type Catalog. So it would only need a search test with an ItemCollection (e.g. from the results of a previous search), no?

**Comment by jsignell** [comment]
Oh! I was thinking about this more and remembered that in pystac `ItemCollection` inherits from `Collection` which in turn inherits from `Catalog`. So I think this is a no-op, but I still like the explicitness.

**Comment by floriandeboissieu** [comment]
> I still like the explicitness

I agree. Thanks for the amendment and the merge.

**Pull request merged**
